{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "signalplane.fullname" . }}
  labels:
    {{- include "signalplane.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "signalplane.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.ingressNamespaceSelector | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
{{- end }}
