{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "signalplane.secretName" . }}
  labels:
    {{- include "signalplane.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secret.keys.ingestToken }}: {{ .Values.secret.values.ingestToken | quote }}
  {{ .Values.secret.keys.bootstrapUserEmail }}: {{ .Values.secret.values.bootstrapUserEmail | quote }}
  {{ .Values.secret.keys.bootstrapUserPassword }}: {{ .Values.secret.values.bootstrapUserPassword | quote }}
  {{ .Values.secret.keys.postgresURL }}: {{ .Values.secret.values.postgresURL | quote }}
  {{ .Values.secret.keys.postgresPassword }}: {{ .Values.secret.values.postgresPassword | quote }}
  {{ .Values.secret.keys.clickhousePassword }}: {{ .Values.secret.values.clickhousePassword | quote }}
{{- end }}
